'use client';
import Link from 'next/link';import Image from 'next/image';import {ArrowRight,BookOpen,Map,School,Mail} from 'lucide-react';import {Section} from '@/components/Section';import {FederationLogo} from '@/components/FederationLogo';import {useLanguage} from '@/components/LanguageProvider';import {guidePublication,lessons,news,t} from '@/lib/content';import {HighlightRibbon} from '@/components/HighlightRibbon';
const concepts=[
 {img:'/images/orienteering/map.jpg',ka:'რუკა',en:'Map',dka:'წაიკითხე რელიეფი და გარემო.',den:'Read the terrain and surroundings.'},
 {img:'/images/orienteering/compass.jpg',ka:'კომპასი',en:'Compass',dka:'განსაზღვრე მიმართულება.',den:'Find your direction.'},
 {img:'/images/orienteering/controls.jpg',ka:'საკონტროლო პუნქტი',en:'Control',dka:'იპოვე საჭირო პუნქტები.',den:'Locate the required controls.'}
];
export default function Home(){const{lang}=useLanguage();return <>
<section className="topo relative overflow-hidden bg-[#0c3026] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_42%,#ef5b2a40,transparent_32%)]"/><div className="container relative grid items-center gap-12 py-14 sm:py-16 md:grid-cols-2 md:gap-10 md:py-20 lg:gap-16"><div><p className="eyebrow mb-4 sm:mb-5">GeOF · GEORGIA</p><h1 className="max-w-2xl text-[clamp(1.85rem,4.8vw,3.35rem)]">{t(lang,'საქართველოს სპორტული ორიენტირების ეროვნული ფედერაცია','Georgian National Orienteering Federation')}</h1><p className="mt-5 max-w-xl text-base text-white/75 sm:mt-6 sm:text-lg">{t(lang,'სპორტი, სადაც ფიზიკური მომზადება, აზროვნება და ბუნებაში ორიენტირების უნარი ერთიანდება.','A sport where physical ability, clear thinking and navigation in nature come together.')}</p><p className="mt-3 text-sm font-bold text-orange-400 sm:text-base">{t(lang,'იპოვე გზა. იპოვე პუნქტი. მიაღწიე მიზანს.','Find the route. Find the control. Reach the goal.')}</p><div className="mt-7 flex flex-wrap gap-3 sm:mt-8"><Link className="btn btn-primary" href="/orienteering">{t(lang,'გაიგე მეტი ორიენტირების შესახებ','Discover orienteering')} <ArrowRight size={17}/></Link><Link className="btn btn-outline" href="/orienteering#learn">{t(lang,'დაიწყე სწავლა','Start learning')}</Link></div></div><div className="flex justify-center md:justify-end"><FederationLogo variant="hero" priority/></div></div></section>
<Section><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">ORIENTEERING 101</p><h2>{t(lang,'რა არის სპორტული ორიენტირება?','What is orienteering?')}</h2><p className="mt-5 text-lg text-slate-600">{t(lang,'მონაწილე დეტალური რუკისა და, ჩვეულებრივ, კომპასის დახმარებით პოულობს საკონტროლო პუნქტებს დადგენილი თანმიმდევრობით. გზას კი თავად ირჩევს.','Using a detailed map and usually a compass, participants visit controls in order—and choose their own route between them.')}</p><Link href="/orienteering" className="mt-6 inline-flex font-bold text-orange-600">{t(lang,'გაიგე მეტი →','Learn more →')}</Link></div><div className="grid gap-4 sm:grid-cols-3">{concepts.map(c=><div className="card overflow-hidden !p-0" key={c.en}><div className="relative aspect-[4/3] bg-[#123d31]/8"><Image src={c.img} alt={t(lang,c.ka,c.en)} fill className="object-cover" sizes="(max-width: 640px) 100vw, 33vw"/></div><div className="p-5"><h3 className="text-xl">{t(lang,c.ka,c.en)}</h3><p className="mt-2 text-sm text-slate-500">{t(lang,c.dka,c.den)}</p></div></div>)}</div></div></Section>
<Section dark className="topo"><div className="max-w-3xl"><p className="eyebrow">HISTORY & ARCHIVE</p><h2>{t(lang,'ორიენტირება საქართველოში','Orienteering in Georgia')}</h2><p className="mt-6 text-white/70">{t(lang,'ორიენტირებას საქართველოში ისტორიული მემკვიდრეობა აქვს. ეს სივრცე შეაგროვებს, გადაამოწმებს და შეინარჩუნებს რუკებს, ფოტოებს, დოკუმენტებსა და ადამიანთა ისტორიებს.','Orienteering has a historical legacy in Georgia. This space will collect, verify and preserve maps, photographs, documents and people’s stories.')}</p><Link className="btn btn-primary mt-8" href="/history#photos">{t(lang,'ფოტოარქივი','Photo archive')} <ArrowRight size={17}/></Link></div><div className="mt-10"><HighlightRibbon lang={lang}/></div></Section>
<Section className="bg-[#f5f3eb]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">LEARNING PATH</p><h2>{t(lang,'ისწავლე ორიენტირება','Learn orienteering')}</h2></div><Link className="font-bold text-orange-600" href="/orienteering#learn">{t(lang,'ყველა გაკვეთილი →','All lessons →')}</Link></div><div className="mt-12 grid gap-4 md:grid-cols-5">{lessons.map((x,i)=><Link href={`/orienteering/${x.slug}`} className="card group" key={x.id}><div className="control mb-7">{i+1}</div><small className="font-bold text-slate-400">LEVEL {x.level}</small><h3 className="mt-2 text-lg group-hover:text-orange-600">{t(lang,x.titleKa,x.titleEn)}</h3><p className="mt-3 text-sm text-slate-500">{t(lang,x.summaryKa,x.summaryEn)}</p></Link>)}</div></Section>
<Section className="bg-[#edf2ee]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">UPDATES</p><h2>{t(lang,'სიახლეები და აქტივობები','News and activities')}</h2></div><Link className="font-bold text-orange-600" href="/news">{t(lang,'ყველა სიახლე →','All news →')}</Link></div><Link href="/news" className="card mt-10 grid overflow-hidden !p-0 md:grid-cols-[240px_1fr]"><div className="bg-[#0c3026] p-6 md:p-8"><Image src={guidePublication.cover} alt={t(lang,guidePublication.titleKa,guidePublication.titleEn)} width={240} height={339} className="mx-auto w-full max-w-[220px] rounded-md shadow-xl"/></div><div className="flex flex-col justify-center p-7 md:p-10"><p className="text-sm font-bold text-orange-600">{t(lang,guidePublication.dateKa,guidePublication.dateEn)}</p><h3 className="mt-3 text-2xl md:text-3xl">{t(lang,news[0].titleKa,news[0].titleEn)}</h3><p className="mt-4 text-slate-600">{t(lang,news[0].summaryKa,news[0].summaryEn)}</p><span className="mt-6 inline-flex font-bold text-orange-600">{t(lang,'სრულად ნახვა →','Read more →')}</span></div></Link></Section>
<Section><div className="grid gap-5 md:grid-cols-3">{[{i:Map,ka:'ისტორიული რუკები',en:'Historical maps',dka:'ინფორმაციები მზადების პროცესშია',den:'Information is being prepared.',href:'/history/maps'},{i:School,ka:'ორიენტირება ახალგაზრდებისთვის',en:'Orienteering for young people',dka:'მოძრაობა, გადაწყვეტილების მიღება და ბუნების გაცნობა.',den:'Movement, decision-making and connection with nature.',href:'/resources'},{i:BookOpen,ka:'რესურსები',en:'Resources',dka:'სასწავლო მასალა, სახელმძღვანელოები და სასარგებლო ბმულები.',den:'Learning material, guides and useful links.',href:'/resources'}].map(({i:I,...x})=><Link href={x.href} className="card" key={x.en}><I className="text-orange-600"/><h3 className="mt-8 text-2xl">{t(lang,x.ka,x.en)}</h3><p className="mt-3 text-slate-500">{t(lang,x.dka,x.den)}</p></Link>)}</div></Section>
<Section dark className="!py-12 md:!py-16"><div className="flex flex-wrap items-center justify-between gap-6"><div><p className="eyebrow">MISSION</p><h2 className="!text-3xl">{t(lang,'ვავითარებთ სპორტს ახალი თაობისთვის','Developing the sport for a new generation')}</h2></div><Link className="btn btn-primary" href="/federation">{t(lang,'ჩვენ შესახებ','About us')} <ArrowRight size={16}/></Link></div></Section>
<Section><div className="rounded-3xl bg-orange-600 p-10 text-white md:flex md:items-center md:justify-between"><div><Mail/><h2 className="mt-4 !text-3xl">{t(lang,'გაქვს მასალა ან გსურს ჩართვა?','Have material to share or want to join?')}</h2></div><Link href="/contact" className="btn mt-6 bg-white text-orange-700 md:mt-0">{t(lang,'დაგვიკავშირდი','Contact us')}</Link></div></Section></>}
