'use client';
import Link from 'next/link';import Image from 'next/image';import {Archive,ArrowRight,BookOpen,CheckCircle2,Clock,Compass,Download,FileText,Flag,Globe2,Map,Mountain,Play,School,Users} from 'lucide-react';import {useLanguage} from './LanguageProvider';import {history,lessons,t,videoGroups} from '@/lib/content';import {Section} from './Section';
const configs:Record<string,{ka:string;en:string;kicker:string;dka:string;den:string}>={
 'federation':{ka:'ფედერაციის შესახებ',en:'About the federation',kicker:'ORGANISATION',dka:'ვქმნით მყარ საფუძველს საქართველოში სპორტული ორიენტირების აღდგენისა და გრძელვადიანი განვითარებისთვის.',den:'Building a strong foundation for the revival and long-term development of orienteering in Georgia.'},
 'history':{ka:'სპორტული ორიენტირების ისტორია საქართველოში',en:'History of orienteering in Georgia',kicker:'HISTORY & MEMORY',dka:'ცოცხალი არქივი, რომელიც ისტორიულ მასალას მხოლოდ წყაროების გადამოწმების შემდეგ გამოაქვეყნებს.',den:'A living archive that publishes historical material only after source verification.'},
 'history/timeline':{ka:'ისტორიული ქრონოლოგია',en:'Historical timeline',kicker:'TIMELINE',dka:'საქართველოს ორიენტირების ისტორიის ეტაპობრივი, წყაროებზე დაფუძნებული დოკუმენტირება.',den:'A gradual, source-based record of Georgian orienteering history.'},
 'history/maps':{ka:'ისტორიული რუკები',en:'Historical maps',kicker:'MAP ARCHIVE',dka:'სივრცე ძველი ორიენტირების რუკების ხარისხიანად შესანახად და შესასწავლად.',den:'A space to preserve and study historical orienteering maps.'},
 'history/people':{ka:'ორიენტირების ადამიანები',en:'People of orienteering',kicker:'ORAL HISTORY',dka:'სპორტსმენების, მწვრთნელების, ორგანიზატორებისა და რუკის შემქმნელების ისტორიებისთვის.',den:'For stories of athletes, coaches, organisers and mapmakers.'},
 'history/archive':{ka:'ისტორიული არქივი',en:'Historical archive',kicker:'PRESERVATION',dka:'ფოტოები, რუკები, შედეგები, სტატიები და ფედერაციის ისტორიული დოკუმენტები.',den:'Photographs, maps, results, articles and federation records.'},
 'orienteering':{ka:'რა არის სპორტული ორიენტირება?',en:'What is orienteering?',kicker:'THE SPORT',dka:'სპორტული ორიენტირება არის რუკითა და კომპასით მოძრაობის სპორტი, რომელიც აერთიანებს ფიზიკურ გამძლეობას, გარემოზე დაკვირვებასა და სწრაფ აზროვნებას.',den:'Sport orienteering is a map-and-compass sport that combines physical endurance, observation of the surroundings and quick thinking.'},
 'learn':{ka:'ისწავლე ორიენტირება',en:'Learn orienteering',kicker:'LEARNING CENTRE',dka:'ნაბიჯ-ნაბიჯ გაიცანი რუკა, კომპასი, მარშრუტის არჩევა და ღონისძიების პროცედურა.',den:'Learn the map, compass, route choice and event procedure step by step.'},
 'learn/map':{ka:'ორიენტირების რუკა',en:'The orienteering map',kicker:'LEVEL 2',dka:'გაიცანი რუკის ფერები, ჰორიზონტალები, ბილიკები, მცენარეულობა, წყალი და სხვა ობიექტები.',den:'Meet map colours, contours, paths, vegetation, water and other features.'},
 'learn/compass':{ka:'კომპასი და მიმართულება',en:'Compass and direction',kicker:'LEVEL 3',dka:'ისწავლე ჩრდილოეთის პოვნა და რუკის გარემოსთან სწორად გასწორება.',den:'Learn to find north and align the map with the terrain.'},
 'learn/controls':{ka:'საკონტროლო პუნქტის აღწერები',en:'Control descriptions',kicker:'LEARNING TOOL',dka:'საკონტროლო აღწერა აზუსტებს, რომელი ობიექტი უნდა იპოვო და სად დგას ნიშანი.',den:'A control description clarifies which feature to find and where the marker is placed.'},
 'learn/route-choice':{ka:'მარშრუტის არჩევა',en:'Route choice',kicker:'LEVEL 4',dka:'შეაფასე მანძილი, რელიეფი, სიჩქარე და შეცდომის რისკი.',den:'Evaluate distance, terrain, speed and the risk of error.'},
 'activities':{ka:'აქტივობები',en:'Activities',kicker:'CURRENT ACTIVITY',dka:'ვარჯიშები, საგანმანათლებლო შეხვედრები და განვითარების პროექტები ეტაპობრივად გამოქვეყნდება.',den:'Training, educational sessions and development projects will be published gradually.'},
 'news':{ka:'სიახლეები',en:'News',kicker:'UPDATES',dka:'ფედერაციის განცხადებები, ახალი მასალები და განვითარების ამბები.',den:'Federation announcements, new material and development updates.'},
 'resources':{ka:'რესურსები',en:'Resources',kicker:'LIBRARY',dka:'სასწავლო მასალების, რუკების, ისტორიული არქივისა და სასარგებლო ბმულების ბიბლიოთეკა.',den:'A library for learning materials, maps, historical records and useful links.'},
 'documents':{ka:'ოფიციალური დოკუმენტები',en:'Official documents',kicker:'GOVERNANCE',dka:'ფედერაციის წესდება, ოქმები, რეგულაციები, განცხადებები და ანგარიშები.',den:'Statute, minutes, regulations, announcements and reports.'},
 'contact':{ka:'კონტაქტი',en:'Contact',kicker:'GET IN TOUCH',dka:'დაგვიკავშირდით ისტორიული მასალის გასაზიარებლად, თანამშრომლობისთვის ან სპორტის გასაცნობად.',den:'Contact us to share historical material, collaborate or discover the sport.'}}
const discipline=[
 {en:'Sprint',ka:'სპრინტი',img:'/images/orienteering/sprint.jpg',den:'A short, fast course, usually held in a park or urban setting. It requires rapid map reading, frequent changes of direction and decisions made in seconds.',dka:'მოკლე და სწრაფი დისტანცია, რომელიც უმეტესად პარკში ან ქალაქის გარემოში ტარდება. მოითხოვს რუკის სწრაფად წაკითხვას, მიმართულების ხშირ ცვლილებასა და წამებში გადაწყვეტილების მიღებას.'},
 {en:'Middle distance',ka:'საშუალო დისტანცია',img:'/images/orienteering/middle.jpg',den:'A technically demanding discipline in forest and varied terrain. The emphasis is on precise navigation, recognising detailed features and controlling direction.',dka:'ტექნიკურად რთული დისციპლინა ტყესა და მრავალფეროვან რელიეფზე. მთავარი აქცენტი კეთდება ზუსტ ნავიგაციაზე, დეტალური ობიექტების ამოცნობასა და მიმართულების კონტროლზე.'},
 {en:'Long distance',ka:'გრძელი დისტანცია',img:'/images/orienteering/long.jpg',den:'A long course with long legs and several possible route choices. It requires endurance, good pacing and choosing the best route.',dka:'ხანგრძლივი დისტანცია გრძელი მონაკვეთებითა და მარშრუტის რამდენიმე შესაძლო ვარიანტით. მონაწილეს სჭირდება გამძლეობა, ტემპის სწორად განაწილება და საუკეთესო მარშრუტის შერჩევა.'},
 {en:'Relay',ka:'ესტაფეტა',img:'/images/orienteering/relay.jpg',den:'A team competition in which members complete the course in turn. Each result affects the team’s overall time, so speed, accuracy and team responsibility matter.',dka:'გუნდური შეჯიბრება, რომელშიც გუნდის წევრები დისტანციას მონაცვლეობით გადიან. თითოეული მონაწილის შედეგი გუნდის საერთო დროზე აისახება, ამიტომ მნიშვნელოვანია სისწრაფე, სიზუსტე და გუნდური პასუხისმგებლობა.'},
 {en:'TrailO',ka:'ტრეილ ორიენტირება — TrailO',img:'/images/orienteering/trailo.jpg',den:'A discipline that tests accurate reading of map and terrain. Speed of movement is not decisive, which makes it accessible to people of different physical abilities.',dka:'დისციპლინა, რომელიც ამოწმებს რუკისა და რელიეფის ზუსტად აღქმის უნარს. გადაადგილების სიჩქარე გადამწყვეტი არ არის, რაც მას სხვადასხვა ფიზიკური შესაძლებლობის მქონე ადამიანებისთვის ხელმისაწვდომს ხდის.'},
 {en:'MTBO',ka:'MTB ორიენტირება — MTBO',img:'/images/orienteering/mtbo.jpg',den:'Orienteering on a mountain bike. Using a specialised map, the participant chooses the best route through a network of roads and paths. It requires fast navigation, good bike handling and safety.',dka:'ორიენტირება სამთო ველოსიპედით. მონაწილე სპეციალური რუკის დახმარებით ირჩევს საუკეთესო მარშრუტს გზებისა და ბილიკების ქსელში. საჭიროა სწრაფი ნავიგაცია, ველოსიპედის კარგად მართვა და უსაფრთხოების წესების დაცვა.'},
 {en:'SkiO',ka:'სათხილამურო ორიენტირება — SkiO',img:'/images/orienteering/skio.jpg',den:'A winter discipline in which the participant moves on skis through a network of prepared tracks. Success requires fast map reading, choosing the right route and moving freely on skis.',dka:'ზამთრის დისციპლინა, რომელშიც მონაწილე თხილამურებით გადაადგილდება მომზადებული ტრასების ქსელში. წარმატებისთვის საჭიროა რუკის სწრაფად წაკითხვა, სწორი მარშრუტის არჩევა და თხილამურებით თავისუფლად გადაადგილება.'}
];
export function InnerPage({slug}:{slug:string}){const{lang}=useLanguage();const c=configs[slug]||configs['learn'];return <><section className="topo bg-[#113a2f] py-24 text-white md:py-32"><div className="container"><p className="eyebrow">{c.kicker}</p><h1 className="mt-4 max-w-5xl text-[clamp(2.5rem,6vw,5rem)]">{t(lang,c.ka,c.en)}</h1><p className="mt-6 max-w-3xl text-lg text-white/70">{t(lang,c.dka,c.den)}</p></div></section>{slug.startsWith('history')?<History lang={lang} slug={slug}/>:slug.startsWith('learn')?<Learn lang={lang} slug={slug}/>:slug==='orienteering'?<Sport lang={lang}/>:slug==='federation'?<Federation lang={lang}/>:slug==='contact'?<Contact lang={lang}/>:<Library lang={lang} slug={slug}/>}</>}
function History({lang,slug}:{lang:'ka'|'en';slug:string}){if(slug==='history/maps'||slug==='history/people')return <Section><Empty icon={slug.endsWith('maps')?Map:Users} title={t(lang,'კოლექციის დამუშავება მიმდინარეობს','Collection in preparation')} text={t(lang,'ჩანაწერები გამოქვეყნდება მასალის მიღების, აღწერისა და წყაროს დადასტურების შემდეგ. მონაცემთა სტრუქტურა მზად არის ფოტოებისთვის, ბიოგრაფიებისთვის, რუკების ავტორებისა და ღონისძიებების მითითებისთვის.','Records will be published after material is received, catalogued and sourced. The data structure is ready for photographs, biographies, cartographers and event references.')}/></Section>;if(slug==='history/archive')return <Section><div className="grid gap-4 md:grid-cols-3">{['ძველი რუკები|Old maps','ისტორიული ფოტოები|Historical photographs','საქართველოს ჩემპიონატები|Georgian championships','საერთაშორისო მონაწილეობა|International participation','დოკუმენტები|Documents','სტატიები და მოგონებები|Articles and memories'].map(x=>{let[a,b]=x.split('|');return <div className="card" key={b}><Archive className="text-orange-600"/><h3 className="mt-8 text-xl">{t(lang,a,b)}</h3><p className="mt-3 text-sm text-slate-500">{t(lang,'კატალოგი მზადდება — ფაქტობრივი მასალა ჯერ არ არის გამოქვეყნებული.','Catalogue in preparation—no factual material is published yet.')}</p></div>})}</div></Section>;return <Section><div className="mb-12 flex flex-wrap gap-3"><Link className="btn bg-[#123d31] text-white" href="/history/timeline">{t(lang,'ქრონოლოგია','Timeline')}</Link><Link className="btn border" href="/history/maps">{t(lang,'რუკები','Maps')}</Link><Link className="btn border" href="/history/people">{t(lang,'ადამიანები','People')}</Link><Link className="btn border" href="/history/archive">{t(lang,'არქივი','Archive')}</Link></div><div className="max-w-4xl">{history.map((x,i)=><article className="relative border-l-2 border-orange-500 pb-14 pl-10" key={x.id}><span className="absolute -left-[9px] top-0 h-4 w-4 rounded-full bg-orange-500"/><span className="rounded-full bg-orange-50 px-3 py-1 text-xs font-bold text-orange-700">{t(lang,'გადასამოწმებელი ჩანაწერი','Awaiting verification')}</span><h2 className="mt-5 !text-3xl">{t(lang,x.titleKa,x.titleEn)}</h2><p className="mt-4 text-slate-600">{t(lang,x.descriptionKa,x.descriptionEn)}</p><p className="mt-4 text-xs font-bold text-slate-400">{t(lang,'წყაროები ჯერ არ არის დართული','No sources attached yet')}</p></article>)}</div></Section>}
function Learn({lang,slug}:{lang:'ka'|'en';slug:string}){const chosen=lessons.find(x=>slug.endsWith(x.slug));return <Section>{chosen&&<div className="mb-12 rounded-2xl bg-[#f5f3eb] p-8"><span className="eyebrow">LEVEL {chosen.level}</span><h2 className="mt-3 !text-3xl">{t(lang,chosen.titleKa,chosen.titleEn)}</h2><div className="mt-7 grid gap-3 md:grid-cols-3">{(lang==='ka'?chosen.contentKa:chosen.contentEn).map(x=><div className="flex gap-2" key={x}><CheckCircle2 className="text-orange-600"/><span>{x}</span></div>)}</div></div>}<div className="grid gap-4 md:grid-cols-5">{lessons.map(x=><Link href={`/learn/${x.slug}`} className="card" key={x.id}><div className="control mb-5">{x.level}</div><h3>{t(lang,x.titleKa,x.titleEn)}</h3><p className="mt-3 text-sm text-slate-500">{t(lang,x.summaryKa,x.summaryEn)}</p></Link>)}</div>{slug==='learn/controls'&&<div className="mt-14 overflow-hidden rounded-xl border"><div className="grid grid-cols-5 bg-[#123d31] p-4 text-sm text-white"><b>#</b><b>{t(lang,'კოდი','Code')}</b><b>{t(lang,'ობიექტი','Feature')}</b><b>{t(lang,'მდებარეობა','Location')}</b><b>{t(lang,'დამატებით','Additional')}</b></div><div className="p-8 text-center text-slate-500">{t(lang,'ოფიციალური სასწავლო მასალის ჩასასმელი კომპონენტი','Component ready for official educational material')}</div></div>}</Section>}
function Sport({lang}:{lang:'ka'|'en'}){return <><Section>
  <div className="max-w-3xl space-y-4 text-lg text-slate-600">
    <p>{t(lang,'მონაწილემ უცნობ ტერიტორიაზე უნდა მოძებნოს წინასწარ განსაზღვრული საკონტროლო პუნქტები და დამოუკიდებლად შეარჩიოს მათ შორის გადაადგილების საუკეთესო გზა.','On unfamiliar terrain, the participant must find predetermined control points and independently choose the best way between them.')}</p>
    <p>{t(lang,'ორიენტირებაში მხოლოდ სწრაფი სირბილი საკმარისი არ არის — წარმატებისთვის საჭიროა ზუსტი ნავიგაცია, სწორი გადაწყვეტილებების მიღება და საკუთარი შესაძლებლობების გონივრულად გამოყენება.','In orienteering, fast running alone is not enough — success requires precise navigation, sound decisions and using one’s abilities wisely.')}</p>
  </div>
  <div className="mt-12 grid gap-5 md:grid-cols-2">{[
    ['რუკა','Map','/images/orienteering/map.jpg','ორიენტირების რუკა არის გარემოს ზუსტი და დეტალური გამოსახულება. მასზე სპეციალური ფერებითა და სიმბოლოებით ნაჩვენებია გზები, ბილიკები, შენობები, ღობეები, წყლის ობიექტები, კლდეები, მცენარეულობა და რელიეფის ფორმები. რუკის მასშტაბი მონაწილეს რეალური მანძილის განსაზღვრაში ეხმარება, ხოლო ჩრდილოეთის ხაზები — რუკის სწორად ორიენტირებაში. რუკის სწრაფად და ზუსტად წაკითხვა ორიენტირების ერთ-ერთი მთავარი უნარია.','An orienteering map is a precise, detailed representation of the terrain. Special colours and symbols show roads, paths, buildings, fences, water features, rocks, vegetation and landforms. Map scale helps judge real distance, and north lines help orient the map correctly. Fast, accurate map reading is one of the core skills of orienteering.'],
    ['კომპასი','Compass','/images/orienteering/compass.jpg','კომპასი აჩვენებს მაგნიტური ჩრდილოეთის მიმართულებას და მონაწილეს რუკის სწორად ორიენტირებაში ეხმარება. მისი გამოყენებით შესაძლებელია მოძრაობის მიმართულების გადამოწმება, კურსის შენარჩუნება და აზიმუტით გადაადგილება. კომპასი არ ცვლის რუკის წაკითხვას. საუკეთესო შედეგი მიიღება მაშინ, როდესაც მონაწილე კომპასის მონაცემებს რუკაზე ნაჩვენებ ობიექტებსა და რეალურ გარემოს ადარებს.','The compass shows magnetic north and helps orient the map correctly. It can be used to check direction of travel, hold a course and move on a bearing. The compass does not replace map reading. The best result comes when compass information is compared with features on the map and the real terrain.'],
    ['საკონტროლო პუნქტები','Controls','/images/orienteering/controls.jpg','საკონტროლო პუნქტები არის მარშრუტზე მოსანახულებელი წინასწარ განსაზღვრული ადგილები. რუკაზე ისინი წრეებით აღინიშნება, ხოლო ადგილზე განთავსებულია ნარინჯისფერ-თეთრი საკონტროლო ალამი და აღრიცხვის მოწყობილობა. მონაწილემ პუნქტები დადგენილი თანმიმდევრობით უნდა გაიაროს და თითოეული მათგანის მონახულება ელექტრონული ჩიპით ან საკონტროლო ბარათით დაადასტუროს. პუნქტის გამოტოვება ან არასწორი თანმიმდევრობით გავლა შედეგზე აისახება.','Control points are predetermined places to visit on the course. On the map they are marked with circles; on the ground there is an orange-and-white control flag and a punching device. The participant must visit the controls in the set order and confirm each visit with an electronic chip or control card. Missing a control or visiting them in the wrong order affects the result.'],
    ['სტარტი და ფინიში','Start and finish','/images/orienteering/start-finish.jpg','ორიენტირების რუკაზე სტარტი სამკუთხედით აღინიშნება. სამკუთხედის ცენტრი მიუთითებს იმ ზუსტ ადგილზე, საიდანაც მარშრუტი იწყება. ფინიში ორმაგი წრით არის მონიშნული. ყველა საჭირო საკონტროლო პუნქტის გავლის შემდეგ მონაწილემ ფინიშის ხაზი უნდა გადაკვეთოს და ელექტრონული აღრიცხვა დაასრულოს.','On an orienteering map the start is marked with a triangle. The centre of the triangle shows the exact place where the course begins. The finish is marked with a double circle. After visiting all required controls, the participant must cross the finish line and complete electronic timing.'],
    ['მარშრუტის არჩევა','Route choice','/images/orienteering/route-choice.jpg','საკონტროლო პუნქტებს შორის მონაწილე საკუთარ მარშრუტს დამოუკიდებლად ირჩევს. შესაძლო გზები შეიძლება განსხვავდებოდეს მანძილით, აღმართის რაოდენობით, მცენარეულობის სიმჭიდროვით, რელიეფის სირთულითა და ნავიგაციის რისკით. უმოკლესი გზა ყოველთვის ყველაზე სწრაფი არ არის. ზოგჯერ შედარებით გრძელი, მაგრამ მარტივი და უსაფრთხო მარშრუტი უკეთესი არჩევანია. სწორედ დამოუკიდებელი დაგეგმვა და სწრაფი გადაწყვეტილებების მიღება ხდის ორიენტირებას „აზროვნების სპორტად“.','Between controls, the participant chooses their own route. Possible ways may differ in distance, climb, vegetation, terrain difficulty and navigation risk. The shortest way is not always the fastest. Sometimes a longer but simpler and safer route is the better choice. Independent planning and quick decisions are what make orienteering a thinking sport.'],
    ['უსაფრთხოება','Safety','/images/orienteering/safety.jpg','უსაფრთხოება ორიენტირების ყველა ვარჯიშისა და შეჯიბრების მთავარი პრიორიტეტია. მონაწილემ წინასწარ უნდა იცოდეს ტერიტორიის საზღვრები, ფინიშზე დაბრუნების დრო, აკრძალული ადგილები, შეხვედრის წერტილი და საგანგებო სიტუაციაში მოქმედების წესი. აუცილებელია ამინდისა და რელიეფის შესაბამისი ტანსაცმელი, გამძლე ფეხსაცმელი და ორგანიზატორის მითითებების დაცვა. თუ მონაწილე დაიკარგა ან დაშავდა, ის უნდა გაჩერდეს, შეაფასოს მდგომარეობა და საჭიროების შემთხვევაში გამოიყენოს სასტვენი ან დაუკავშირდეს ორგანიზატორს.','Safety is the main priority at every orienteering training and competition. The participant should know in advance the area boundaries, the time to return to the finish, forbidden areas, the meeting point and what to do in an emergency. Appropriate clothing, sturdy shoes and following the organiser’s instructions are essential. If lost or injured, stop, assess the situation and, if needed, use a whistle or contact the organiser.']
  ].map(x=><article className="card overflow-hidden !p-0" key={x[1]}><div className="relative aspect-[16/10] bg-[#123d31]/10"><Image src={x[2]} alt={t(lang,x[0],x[1])} fill className="object-contain p-1" sizes="(max-width: 768px) 100vw, 50vw"/></div><div className="p-6"><h3 className="text-xl">{t(lang,x[0],x[1])}</h3><p className="mt-3 text-slate-600">{t(lang,x[3],x[4])}</p></div></article>)}</div>
</Section><Section className="bg-[#f5f3eb]"><h2>{t(lang,'დისციპლინები','Disciplines')}</h2><p className="mt-4 max-w-3xl text-slate-600">{t(lang,'სასწავლო მასალის ძირითადი აქცენტი კეთდება ფეხით ორიენტირებაზე, რომელიც მოიცავს სპრინტს, საშუალო და გრძელ დისტანციებსა და ესტაფეტას.','The main educational focus is on foot orienteering, which includes sprint, middle and long distance, and relay.')}</p><div className="mt-10 grid gap-4 md:grid-cols-2">{discipline.map(x=><article className="card overflow-hidden !p-0" key={x.en}><div className="relative aspect-[16/10] bg-[#123d31]/10"><Image src={x.img} alt={t(lang,x.ka,x.en)} fill className="object-contain p-1" sizes="(max-width: 768px) 100vw, 50vw"/></div><div className="p-6"><h3 className="text-xl">{t(lang,x.ka,x.en)}</h3><p className="mt-3 text-slate-600">{t(lang,x.dka,x.den)}</p></div></article>)}</div><p className="mt-8 text-xs text-slate-400">{t(lang,'ილუსტრაციები: Wikimedia Commons (თავისუფალი ლიცენზია).','Illustrations: Wikimedia Commons (free licence).')}</p></Section></>}
function Federation({lang}:{lang:'ka'|'en'}){
  const blocks=[
    {ka:'ვინ ვართ',en:'Who we are',img:'/images/federation/who-we-are.png',dka:'საქართველოს სპორტული ორიენტირების ეროვნული ფედერაცია აერთიანებს სპორტსმენებს, მწვრთნელებს, მსაჯებს, მასწავლებლებს, კლუბებსა და სპორტის გულშემატკივრებს. ვქმნით ღია, სანდო და საგანმანათლებლო სივრცეს ორიენტირების შესწავლის, განვითარებისა და პოპულარიზაციისთვის.',den:'The Georgian National Orienteering Federation brings together athletes, coaches, officials, teachers, clubs and supporters of the sport. We create an open, trusted educational space for learning, developing and promoting orienteering.'},
    {ka:'ჩვენი მიზანი',en:'Our goal',img:'/images/federation/our-goal.png',dka:'ჩვენი მიზანია სპორტული ორიენტირების თანმიმდევრული განვითარება საქართველოს მასშტაბით — სასკოლო პროგრამებისა და ახალი კლუბების მხარდაჭერა, მოსწავლეთა აქტივობებისა და შეჯიბრებების ორგანიზება, მასწავლებლების მომზადება და სპორტის რეგიონებში გავრცელება.',den:'Our goal is the consistent development of sport orienteering across Georgia — supporting school programmes and new clubs, organising student activities and competitions, preparing teachers and spreading the sport in the regions.'},
    {ka:'ჩვენი მისია',en:'Our mission',img:'/images/federation/our-mission.png',dka:'ჩვენი მისიაა ქართული ორიენტირების მემკვიდრეობის დაცვა, ახალი თაობისთვის ცოდნისა და გამოცდილების გადაცემა, ქართულენოვანი სასწავლო-მეთოდური ლიტერატურის შექმნა და ძლიერი, განათლებული სპორტული საზოგადოების ჩამოყალიბება.',den:'Our mission is to protect the heritage of Georgian orienteering, pass knowledge and experience to a new generation, create Georgian-language teaching materials and build a strong, educated sporting community.'}
  ];
  return <><Section><div className="grid gap-14">{blocks.map((x,i)=><article key={x.en} className="grid items-center gap-8 md:grid-cols-2"><div className={`relative aspect-[4/3] overflow-hidden rounded-2xl bg-slate-100 ${i%2===1?'md:order-2':''}`}><Image src={x.img} alt={t(lang,x.ka,x.en)} fill className="object-cover object-center" sizes="(max-width: 768px) 100vw, 50vw"/></div><div><h2 className="!text-3xl">{t(lang,x.ka,x.en)}</h2><p className="mt-4 text-lg leading-relaxed text-slate-600">{t(lang,x.dka,x.den)}</p></div></article>)}</div></Section><Section className="bg-[#f5f3eb]"><h2>{t(lang,'საქმიანობის მიმართულებები','Areas of work')}</h2><div className="mt-9 grid gap-4 md:grid-cols-4">{['სპორტის განვითარება|Sport development','ახალგაზრდები და სკოლები|Youth and schools','სწავლება|Education','რუკების შექმნა|Mapmaking','შეჯიბრებები|Competitions','ისტორიული მემკვიდრეობა|Historical legacy','საერთაშორისო თანამშრომლობა|International cooperation'].map(x=>{let[a,b]=x.split('|');return <div className="card" key={b}><Compass className="text-orange-600"/><b className="mt-6 block">{t(lang,a,b)}</b></div>})}</div><div className="mt-14"><h2 className="!text-3xl">{t(lang,'ხელმძღვანელობა და სტრუქტურა','Leadership and structure')}</h2><Empty icon={Users} title={t(lang,'ინფორმაცია მზადდება','Information in preparation')} text={t(lang,'სახელები და ბიოგრაფიები გამოქვეყნდება მხოლოდ ოფიციალური დადასტურების შემდეგ.','Names and biographies will be published only after official confirmation.')}/></div></Section></>}
function Library({lang,slug}:{lang:'ka'|'en';slug:string}){
  const isActivity=slug==='activities',isNews=slug==='news';
  if(isActivity||isNews)return <Section><Empty icon={isActivity?Clock:BookOpen} title={t(lang,isActivity?'ახალი აქტივობები მალე გამოქვეყნდება':'სიახლეების არქივი მზადდება',isActivity?'New activities coming soon':'News archive in preparation')} text={t(lang,isActivity?'არ ვქმნით გამოგონილ ღონისძიებებს. გადამოწმებული ვარჯიშები და შეხვედრები გამოქვეყნებისთანავე აქ გამოჩნდება.':'ფედერაციის გადამოწმებული განცხადებები და მასალები გამოქვეყნებისთანავე აქ გამოჩნდება.',isActivity?'We do not create fictional events. Verified training and meetings will appear here as they are announced.':'Verified federation announcements and materials will appear here as published.')}/></Section>;
  if(slug==='documents'){
    const items=['წესდება|Statute','ოქმები|Minutes','რეგულაციები|Regulations','ოფიციალური განცხადებები|Official announcements','განვითარების გეგმები|Development plans','წლიური ანგარიშები|Annual reports'];
    return <Section><div className="grid gap-4 md:grid-cols-3">{items.map(x=>{let[a,b]=x.split('|');return <div className="card" key={b}><FileText className="text-orange-600"/><h3 className="mt-8 text-xl">{t(lang,a,b)}</h3><p className="mt-3 text-sm text-slate-500">{t(lang,'მასალა დაემატება გამოქვეყნების შემდეგ.','Material will appear when published.')}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-slate-400"><Download size={14}/> {t(lang,'ჯერ არ არის ფაილები','No files yet')}</span></div>})}</div></Section>;
  }
  const items=['სასწავლო მასალები|Learning materials','რუკები|Maps','ისტორიული მასალები|Historical materials','ოფიციალური დოკუმენტები|Official documents','სასარგებლო ბმულები|Useful links','სახელმძღვანელოები|Guides'];
  return <>
    <Section>
      <div className="grid gap-4 md:grid-cols-3">{items.map(x=>{let[a,b]=x.split('|');return <div className="card" key={b}><FileText className="text-orange-600"/><h3 className="mt-8 text-xl">{t(lang,a,b)}</h3><p className="mt-3 text-sm text-slate-500">{t(lang,'მასალა დაემატება გამოქვეყნების შემდეგ.','Material will appear when published.')}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-slate-400"><Download size={14}/> {t(lang,'ჯერ არ არის ფაილები','No files yet')}</span></div>})}<a href="#videos" className="card border-orange-200 bg-orange-50/40"><Play className="text-orange-600"/><h3 className="mt-8 text-xl">{t(lang,'ვიდეოები','Videos')}</h3><p className="mt-3 text-sm text-slate-500">{t(lang,'სასწავლო ვიდეოები დამწყებთათვის, მასწავლებლებისა და მწვრთნელებისთვის.','Learning videos for beginners, teachers and coaches.')}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-orange-600">{t(lang,'იხილეთ ქვემოთ →','See below →')}</span></a></div>
    </Section>
    <Section className="bg-[#f5f3eb]" id="videos">
      <p className="eyebrow">VIDEO LIBRARY</p>
      <h2>{t(lang,'სასწავლო ვიდეოები','Learning videos')}</h2>
      <p className="mt-4 max-w-3xl text-slate-600">{t(lang,'ვიდეოები ინგლისურენოვანია. უმეტესობაზე შესაძლებელია YouTube-ის ავტომატური სუბტიტრებისა და თარგმანის ჩართვა.','The videos are in English. On most of them you can turn on YouTube automatic captions and translation.')}</p>
      <div className="mt-12 grid gap-16">{videoGroups.map(group=><div key={group.id}><h3 className="mb-6 text-2xl">{t(lang,group.ka,group.en)}</h3><div className="grid gap-6 md:grid-cols-2">{group.videos.map(v=>{const src=v.playlistId?`https://www.youtube.com/embed/videoseries?list=${v.playlistId}`:`https://www.youtube.com/embed/${v.youtubeId}`;const href=v.playlistId?`https://www.youtube.com/playlist?list=${v.playlistId}`:`https://www.youtube.com/watch?v=${v.youtubeId}`;return <article className="card overflow-hidden p-0" key={v.id}><div className="aspect-video bg-black"><iframe className="h-full w-full" src={src} title={t(lang,v.titleKa,v.titleEn)} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen loading="lazy"/></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-wide text-orange-600">{t(lang,v.topicKa,v.topicEn)}</p>{v.orgKa&&<p className="mt-1 text-xs text-slate-400">{t(lang,v.orgKa,v.orgEn||v.orgKa)}</p>}<h3 className="mt-3 text-xl">{t(lang,v.titleKa,v.titleEn)}</h3><p className="mt-3 text-sm text-slate-600">{t(lang,v.descriptionKa,v.descriptionEn)}</p><a className="mt-5 inline-flex items-center gap-2 font-bold text-orange-600" href={href} target="_blank" rel="noopener noreferrer">{t(lang,'ვიდეოს ნახვა YouTube-ზე','Watch on YouTube')} <ArrowRight size={16}/></a></div></article>})}</div></div>)}</div>
    </Section>
  </>;
}
function Contact({lang}:{lang:'ka'|'en'}){return <Section><div className="grid gap-14 md:grid-cols-2"><div><h2 className="!text-3xl">{t(lang,'საკონტაქტო ინფორმაცია','Contact information')}</h2><dl className="mt-8 grid gap-5"><div><dt className="text-xs font-bold text-slate-400">FEDERATION</dt><dd>{t(lang,'საქართველოს სპორტული ორიენტირების ეროვნული ფედერაცია','Georgian National Orienteering Federation')}</dd></div><div><dt className="text-xs font-bold text-slate-400">EMAIL</dt><dd><a href="mailto:geoorgineeting@gmail.com" className="text-orange-600 hover:underline">geoorgineeting@gmail.com</a></dd></div><div><dt className="text-xs font-bold text-slate-400">PHONE</dt><dd><a href="tel:+995577133493" className="text-slate-700 hover:text-orange-600">+995 577 133 493</a></dd></div><div><dt className="text-xs font-bold text-slate-400">FACEBOOK</dt><dd><a href="https://www.facebook.com/GeoOrienteering" target="_blank" rel="noopener noreferrer" className="text-slate-700 hover:text-orange-600">GeoOrienteering</a></dd></div><div><dt className="text-xs font-bold text-slate-400">ADDRESS</dt><dd className="text-slate-700">{t(lang,'ნიკეას ქუჩა 72/59, ქუთაისი, საქართველო','72/59 Nikea street, Kutaisi, Georgia')}</dd></div></dl></div><form className="card" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const name=f.get('name');const email=f.get('email');const subject=f.get('subject');const message=f.get('message');window.location.href=`mailto:geoorgineeting@gmail.com?subject=${encodeURIComponent(String(subject))}&body=${encodeURIComponent(`Name: ${name}\nEmail: ${email}\n\nMessage:\n${message}`)}`;}}><div className="grid gap-5"><label>{t(lang,'სახელი','Name')}<input name="name" required/></label><label>{t(lang,'ელფოსტა','Email')}<input name="email" type="email" required/></label><label>{t(lang,'თემა','Subject')}<input name="subject" required/></label><label>{t(lang,'შეტყობინება','Message')}<textarea name="message" rows={5} required/></label><button className="btn btn-primary w-fit" type="submit">{t(lang,'გაგზავნა','Send')} <ArrowRight size={16}/></button><small className="text-slate-400">{t(lang,'ღილაკზე დაჭერით გაიხსნება თქვენი ელფოსტის პროგრამა შევსებული მონაცემებით.','Clicking the button will open your email application with the filled details.')}</small></div></form></div></Section>}
function Empty({icon:I,title,text}:{icon:typeof Archive;title:string;text:string}){return <div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-[#f8faf8] p-10 text-center"><I className="mx-auto text-orange-600" size={42}/><h3 className="mt-5 text-xl">{title}</h3><p className="mx-auto mt-3 max-w-2xl text-slate-500">{text}</p></div>}
