import {Activity, HistoryEntry, HistoricalMap, HistoricalPerson, LearningLesson, NewsArticle} from './types';
export type Lang='ka'|'en'; export const t=(l:Lang,ka:string,en:string)=>l==='ka'?ka:en;
export const nav=[['/','მთავარი','Home'],['/federation','ფედერაცია','Federation'],['/history','ისტორია','History'],['/orienteering','ორიენტირება','Orienteering'],['/learn','სწავლა','Learn'],['/activities','აქტივობები','Activities'],['/news','სიახლეები','News'],['/resources','რესურსები','Resources'],['/contact','კონტაქტი','Contact']];
// FACTUAL PLACEHOLDERS: no unverified names, dates, results or affiliations are published.
export const history:HistoryEntry[]=[
 {id:'beginnings',titleKa:'სპორტული ორიენტირების დასაწყისი საქართველოში',titleEn:'The beginnings of orienteering in Georgia',descriptionKa:'მასალა დამუშავების პროცესშია — პერიოდი, წყაროები და მონაწილეთა მოგონებები დაემატება მხოლოდ გადამოწმების შემდეგ.',descriptionEn:'Research in progress — dates, sources and recollections will be added only after verification.',images:[],people:[],documents:[],maps:[],source:[],verified:false},
 {id:'new-stage',titleKa:'სპორტის აღდგენა და ახალი ეტაპი',titleEn:'Revival and a new chapter',descriptionKa:'ფედერაცია აგროვებს დოკუმენტურ მასალას და ქმნის ახალ საგანმანათლებლო სივრცეს. დეტალური ქრონოლოგია გამოქვეყნდება წყაროების დადასტურების შემდეგ.',descriptionEn:'The federation is collecting documentary material and building a new educational space. A detailed chronology will follow source verification.',images:[],people:[],documents:[],maps:[],source:[],verified:false}];
export const maps:HistoricalMap[]=[]; export const people:HistoricalPerson[]=[]; export const activities:Activity[]=[]; export const news:NewsArticle[]=[];
export const lessons:LearningLesson[]=[
 {id:'first',slug:'first-steps',level:1,order:1,titleKa:'პირველი ნაბიჯები',titleEn:'First steps',summaryKa:'გაიგე რუკის, სტარტის, ფინიშისა და საკონტროლო პუნქტის არსი.',summaryEn:'Meet the map, start, finish and control point.',contentKa:['რა არის რუკა?','რუკის ორიენტირება','მარტივი მარშრუტი'],contentEn:['What is a map?','Orienting the map','A simple route'],images:[],downloadableResources:[]},
 {id:'map',slug:'map',level:2,order:2,titleKa:'რუკის კითხვა',titleEn:'Reading the map',summaryKa:'ფერები, პირობითი ნიშნები, რელიეფი და მასშტაბი.',summaryEn:'Colours, symbols, terrain and scale.',contentKa:['რუკის ფერები','ჰორიზონტალები','ბილიკები და რელიეფი'],contentEn:['Map colours','Contour lines','Paths and terrain'],images:[],downloadableResources:[]},
 {id:'compass',slug:'compass',level:3,order:3,titleKa:'კომპასი',titleEn:'Compass',summaryKa:'ჩრდილოეთი, მიმართულება და რუკის სწორად დაჭერა.',summaryEn:'North, direction and keeping the map oriented.',contentKa:['კომპასის ნაწილები','ჩრდილოეთი','მიმართულება'],contentEn:['Compass parts','North','Direction'],images:[],downloadableResources:[]},
 {id:'route',slug:'route-choice',level:4,order:4,titleKa:'მარშრუტის არჩევა',titleEn:'Route choice',summaryKa:'სისწრაფესა და საიმედოობას შორის გააზრებული არჩევანი.',summaryEn:'Make a considered choice between speed and reliability.',contentKa:['საყრდენი ხაზები','შეტევის წერტილი','მანძილის შეფასება'],contentEn:['Handrails','Attack points','Distance estimation'],images:[],downloadableResources:[]},
 {id:'race',slug:'competition',level:5,order:5,titleKa:'შეჯიბრისთვის მზადება',titleEn:'Getting event-ready',summaryKa:'სტარტის პროცედურა, აღნიშვნა, ფინიში და უსაფრთხოება.',summaryEn:'Start procedure, punching, finish and safety.',contentKa:['სტარტი','აღნიშვნა','ფინიში და შედეგები'],contentEn:['Start','Punching','Finish and results'],images:[],downloadableResources:[]}];
