export interface SourceReference { type:'document'|'article'|'photograph'|'interview'|'federation-archive'|'external-archive'|'publication'; title:string; url?:string }
export interface HistoryEntry { id:string; year?:string; yearEnd?:string; titleKa:string; titleEn:string; descriptionKa:string; descriptionEn:string; images:string[]; people:string[]; documents:string[]; maps:string[]; source:SourceReference[]; verified:boolean }
export interface HistoricalPerson { id:string; nameKa:string; nameEn:string; photo?:string; roleKa:string; roleEn:string; period?:string; biographyKa:string; biographyEn:string; achievements:string[]; sources:SourceReference[] }
export interface HistoricalMap { id:string; titleKa:string; titleEn:string; year?:string; location?:string; cartographer?:string; event?:string; image?:string; descriptionKa:string; descriptionEn:string }
export interface Activity { id:string; slug:string; titleKa:string; titleEn:string; date?:string; locationKa?:string; locationEn?:string; category:string; status:'planned'|'ongoing'|'completed'; image?:string; descriptionKa:string; descriptionEn:string }
export interface LearningLesson { id:string; slug:string; level:number; order:number; titleKa:string; titleEn:string; summaryKa:string; summaryEn:string; contentKa:string[]; contentEn:string[]; images:string[]; downloadableResources:string[] }
export interface NewsArticle { id:string; slug:string; titleKa:string; titleEn:string; summaryKa:string; summaryEn:string; contentKa:string[]; contentEn:string[]; image?:string; category:string; publishedAt?:string }
export interface VideoResource { id:string; youtubeId?:string; playlistId?:string; titleKa:string; titleEn:string; topicKa:string; topicEn:string; descriptionKa:string; descriptionEn:string; orgKa?:string; orgEn?:string }
export interface UsefulLink { id:string; featured?:boolean; title:string; url:string; ctaKa:string; ctaEn:string; descriptionKa:string; descriptionEn:string }
